# Generated by Django 4.2.2 on 2023-06-10 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fulfilled', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=users.models._get_expiration_time)),
                ('email_type', models.IntegerField(choices=[(1, 'LOGIN'), (2, 'VERIFICATION')], default=users.models.UserLoginEmailType['LOGIN'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userloginemail',
            constraint=models.UniqueConstraint(condition=models.Q(('fulfilled', False)), fields=('user',), name='user_active_login_email'),
        ),
    ]
