# Generated by Django 4.2.2 on 2023-07-07 18:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userloginemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'UNVERIFIED'), (2, 'VERIFIED'), (3, 'UNSUBSCRIBED'), (4, 'BLOCKLISTED'), (5, 'DENIED_PLAN')], default=users.models.UserStatus['UNVERIFIED']),
        ),
    ]
