# Generated by Django 4.2.2 on 2023-07-10 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeReminderEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fulfilled', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField()),
                ('unique_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='practicereminderemail',
            constraint=models.UniqueConstraint(fields=('user', 'unique_key'), name='practice_reminder_email_key'),
        ),
    ]
