# Generated by Django 4.2.2 on 2023-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_practicereminderemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicereminderemail',
            name='expires_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
