# Generated by Django 4.2.2 on 2023-07-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_practicereminderemail_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicereminderemail',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
