# Generated by Django 4.2.2 on 2023-07-19 21:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_practicereminderemail_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'UNVERIFIED'), (2, 'VERIFIED'), (3, 'BLOCKLISTED'), (4, 'DENIED_PLAN')], default=users.models.UserStatus['UNVERIFIED']),
        ),
    ]
