# Generated by Django 4.2.2 on 2023-08-01 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginemail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 16, 10, 1, 820888, tzinfo=datetime.timezone.utc)),
        ),
    ]
