# Generated by Django 4.2.2 on 2023-08-01 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userloginemail_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginemail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
