FROM alpine:3.17.3

# npm
RUN apk update && apk add npm

WORKDIR /usr/app

# Install dependencies
COPY package.json .
COPY package-lock.json .

RUN npm install --production=false

CMD ["npm", "run", "dev"]
