version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - ./grammargrove/log:/var/log/uwsgi
    ports:
      - 8000:8000
    environment:
      - ENV=dev
      - DATABASE_HOST=database
      - DATABASE_POST=5432
      - DATABASE_NAME=appdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - SES_ACCESS_KEY_ID=$SES_ACCESS_KEY
      - SES_SECRET_ACCESS_KEY=$SES_ACCESS_SECRET
      - SES_REGION=us-east-1
      - SES_DEFAULT_SENDER_ADDRESS=andrew@indieorchard.com
      - OPENAI_API_KEY=$GRAMMARGROVE_OPENAI_API_KEY
      - STRIPE_API_KEY=$GRAMMARGROVE_STRIPE_SECRET_KEY
      - GRECAPTCHA_SECRET_KEY=$GRAMMARGROVE_RECAPTCHA_SECRET_KEY
      - GIT_SHA=$GRAMMARGROVE_GIT_SHA
    depends_on:
      - database
    command: scripts/runserver
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./index/static:/usr/app/dist
      - ./frontend:/usr/app
      - /usr/app/node_modules
  database:
    build:
      dockerfile: ./index/migrations/Dockerfile.dev
      context: ./
    volumes:
      - ./index/migrations/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

