FROM python:3.10.12-bullseye

WORKDIR /app

RUN apt-get update -y && apt-get install -y postgresql
RUN pip3 install poetry

COPY pyproject.toml .
COPY poetry.lock .

RUN poetry install

RUN [ "/bin/sh" ]
