version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./grammargrove/log:/var/log/uwsgi
      - ./grammargrove/uwsgi:/var/uwsgi
      - static-files:/app/index/static
    restart: unless-stopped
    networks:
      - web_default
    depends_on:
      - database
    env_file:
      - env/web.env
    environment:
      - GIT_SHA=$GRAMMARGROVE_GIT_SHA
  proxy:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./grammargrove/uwsgi:/var/uwsgi
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
      - static-files:/www/data/static
    depends_on:
      - web
    networks:
      - web_default
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - proxy
    command: certonly --webroot --webroot-path=/var/www/html --email deaver.andrew@gmail.com --agree-tos --no-eff-email --force-renewal -d grammargrove.com -d www.grammargrove.com -v
    networks:
      - web_default
  database:
    image: postgres:12.12
    restart: always
    env_file:
      - env/db.env
    volumes:
      - ./index/migrations/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - web_default

volumes:
  static-files:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/grammargrove/grammargrove/webroot/dhparam/
      o: bind

networks:
  web_default:
    driver: bridge
