version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./grammargrove/log:/var/log/uwsgi
      - ./grammargrove/uwsgi:/var/uwsgi
    restart: unless-stopped
    networks:
      - web_default
    depends_on:
      - database
    env_file:
      - env/web.env
  proxy:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./grammargrove/uwsgi:/var/uwsgi
    depends_on:
      - web
    networks:
      - web_default
  database:
    image: postgres:12.12
    restart: always
    volumes:
      - ./index/migrations/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - web_default

networks:
  web_default:
    driver: bridge
