version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./grammargrove/log:/var/log/uwsgi
      - ./grammargrove/uwsgi:/var/uwsgi
    restart: unless-stopped
    networks:
      - web_default
    environment:
      - ENV=prod
      - DJANGO_SECRET_KEY=$GRAMMARGROVE_DJANGO_SECRET_KEY
  proxy:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./grammargrove/uwsgi:/var/uwsgi
    depends_on:
      - web
    networks:
      - web_default
  database:
    build:
      dockerfile: ./index/migrations/Dockerfile.dev
      context: ./
    volumes:
      - ./index/migrations/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - web_default

networks:
  web_default:
    driver: bridge
