# Generated by Django 4.2.2 on 2023-07-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergrammarrules', '0005_remove_usergrammarruleentry_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrammarrulenote',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
