# Generated by Django 4.2.2 on 2023-06-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uservocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.IntegerField(choices=[(1, 'AccentsFromHanzi'), (2, 'DefinitionsFromHanzi'), (3, 'HanziFromEnglish')])),
                ('number_of_times_displayed', models.IntegerField(default=1)),
                ('number_of_times_answered_correctly', models.IntegerField(default=0)),
                ('last_displayed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_answered_correctly_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_vocabulary_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uservocabulary.uservocabularyentry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('user_vocabulary_entry__isnull', False)), fields=('user', 'user_vocabulary_entry', 'question_type'), name='question_type_idx'),
        ),
    ]
