# Generated by Django 4.2.2 on 2023-06-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usergrammarrules', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='user_grammar_rule_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usergrammarrules.usergrammarruleentry'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('user_grammar_rule_entry__isnull', False)), fields=('user', 'user_grammar_rule_entry', 'question_type'), name='grammar_rule_question_type_idx'),
        ),
    ]
