# Generated by Django 4.2.2 on 2023-07-01 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0009_alter_grammarrule_language_code_and_more'),
        ('quiz', '0005_rename_last_displayed_at_quizresponse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='example_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarruleexample'),
        ),
    ]
