# Generated by Django 4.2.2 on 2023-07-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practicesession', '0001_initial'),
        ('quiz', '0007_rename_example_id_quizresponse_grammar_rule_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='practice_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practicesession.practicesession'),
        ),
    ]
