# Generated by Django 4.2.2 on 2023-07-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quizresponse_practice_session'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizresponse',
            index=models.Index(fields=['practice_session'], name='quiz_quizre_practic_a2af19_idx'),
        ),
    ]
