# Generated by Django 4.2.2 on 2023-06-12 13:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('language_code', models.TextField(choices=[('ZHCHS', 'SIMPLIFIED_MANDARIN'), ('ZHCHT', 'TRADITIONAL_MANDARIN'), ('ENG', 'ENGLISH')])),
                ('display', models.TextField()),
                ('pronunciation', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['language_code', 'display'], name='words_word_languag_bbc5f4_idx'), models.Index(fields=['language_code', 'pronunciation'], name='words_word_languag_abeae2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.TextField(choices=[('ZHCHS', 'SIMPLIFIED_MANDARIN'), ('ZHCHT', 'TRADITIONAL_MANDARIN'), ('ENG', 'ENGLISH')])),
                ('definition', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'indexes': [models.Index(fields=['word'], name='words_defin_word_id_4e5bd0_idx'), models.Index(fields=['word', 'language_code'], name='words_defin_word_id_86c33a_idx')],
            },
        ),
    ]
