# Generated by Django 4.2.2 on 2023-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='language_code',
            field=models.TextField(choices=[('ZHCHS', 'Simplified'), ('ZHCHT', 'Traditional'), ('ENG', 'English')]),
        ),
        migrations.AlterField(
            model_name='word',
            name='language_code',
            field=models.TextField(choices=[('ZHCHS', 'Simplified'), ('ZHCHT', 'Traditional'), ('ENG', 'English')]),
        ),
    ]
