# Generated by Django 4.2.2 on 2023-06-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_definition_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='words.word'),
        ),
    ]
