# Generated by Django 4.2.2 on 2023-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_definition_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hsk_level',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
