# Generated by Django 4.2.2 on 2023-07-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_word_hsk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='contains_hanzi',
            field=models.BooleanField(default=False),
        ),
    ]
