# Generated by Django 4.2.2 on 2023-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_definition_contains_hanzi'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='definition',
            index=models.Index(condition=models.Q(('contains_hanzi', False)), fields=['word'], name='contains_hanzi_idx'),
        ),
    ]
