# Generated by Django 4.2.2 on 2023-07-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_definition_contains_hanzi_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
