# Generated by Django 4.2.2 on 2023-07-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.TextField(choices=[('grammar_rule_fetches_enabled', 'grammar_rule_fetches_enabled')], editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(null=True)),
            ],
        ),
    ]
