# Generated by Django 4.2.2 on 2023-08-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_alter_featureflag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='id',
            field=models.TextField(choices=[('grammar_rule_fetches_enabled', 'grammar_rule_fetches_enabled'), ('practice_reminder_emails_enabled', 'practice_reminder_emails_enabled'), ('recaptcha_enabled', 'recaptcha_enabled'), ('grammar_rule_scavenger_enabled', 'grammar_rule_scavenger_enabled'), ('grammar_rule_validation_enabled', 'grammar_rule_validation_enabled'), ('use_only_high_quality_grammar_rules_examples_enabled', 'use_only_high_quality_grammar_rules_examples_enabled')], editable=False, primary_key=True, serialize=False),
        ),
    ]
