# Generated by Django 4.2.2 on 2023-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_featureflag_flag_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.CheckConstraint(check=models.Q(('enabled__isnull', False), ('flag_type', 'boolean')), name='valid'),
        ),
    ]
