# Generated by Django 4.2.4 on 2023-08-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_featureflag_valid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='featureflag',
            name='valid',
        ),
        migrations.AddField(
            model_name='featureflag',
            name='int_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('enabled__isnull', False), ('flag_type', 'boolean')), models.Q(('flag_type', 'integer'), ('int_value__isnull', False)), _connector='OR'), name='valid'),
        ),
    ]
