# Generated by Django 4.2.4 on 2023-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_alter_featureflag_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='featureflag',
            name='valid',
        ),
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('enabled__isnull', False), ('flag_type', 'boolean'), ('int_value__isnull', True)), models.Q(('enabled__isnull', True), ('flag_type', 'integer'), ('int_value__isnull', False)), _connector='OR'), name='valid'),
        ),
    ]
