# Generated by Django 4.2.4 on 2023-08-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_remove_featureflag_valid_featureflag_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
