# Generated by Django 4.2.2 on 2023-06-17 16:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRuleExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_idx', models.IntegerField()),
                ('hanzi_display', models.TextField()),
                ('pinyin_display', models.TextField()),
                ('english_definition', models.TextField()),
                ('parse_version', models.IntegerField(choices=[(1, 'Version1')], null=True)),
                ('parse_error', models.TextField(null=True)),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarrule')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRuleExamplePrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField(null=True)),
                ('model', models.TextField()),
                ('usage_tokens', models.IntegerField()),
                ('language_code', models.TextField(choices=[('ZHCHS', 'SIMPLIFIED_MANDARIN'), ('ZHCHT', 'TRADITIONAL_MANDARIN'), ('ENG', 'ENGLISH')])),
                ('parse_version', models.IntegerField(choices=[(1, 'Version1')], null=True)),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarrule')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRuleExampleComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('example_index', models.IntegerField()),
                ('grammar_rule_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarruleexample')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
        migrations.AddField(
            model_name='grammarruleexample',
            name='grammar_rule_example_prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarruleexampleprompt'),
        ),
        migrations.CreateModel(
            name='GrammarRuleComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_of_speech', models.IntegerField(choices=[(1, 'Noun'), (2, 'Pronoun'), (3, 'Verb'), (4, 'Adjective'), (5, 'Adverb'), (6, 'NumberWord'), (7, 'Interjection'), (8, 'Onomatopoeia'), (9, 'FunctionWord'), (10, 'Conjunction'), (11, 'MeasureWord'), (12, 'Preposition'), (13, 'Particle'), (14, 'Predicate'), (15, 'Subject'), (16, 'Object')], null=True)),
                ('rule_index', models.IntegerField()),
                ('optional', models.BooleanField(default=False)),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarrule')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
        migrations.AddIndex(
            model_name='grammarruleexampleprompt',
            index=models.Index(fields=['grammar_rule'], name='grammarrule_grammar_88767b_idx'),
        ),
        migrations.AddConstraint(
            model_name='grammarruleexamplecomponent',
            constraint=models.UniqueConstraint(fields=('grammar_rule_example', 'example_index'), name='grammar_rule_example_component_index_unique'),
        ),
        migrations.AddIndex(
            model_name='grammarruleexample',
            index=models.Index(fields=['grammar_rule'], name='grammarrule_grammar_20fba3_idx'),
        ),
        migrations.AddConstraint(
            model_name='grammarruleexample',
            constraint=models.UniqueConstraint(fields=('grammar_rule_example_prompt', 'line_idx'), name='grammar_rule_example_line_index_unique'),
        ),
        migrations.AddIndex(
            model_name='grammarrulecomponent',
            index=models.Index(fields=['word'], name='grammarrule_word_id_5a2a57_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarrulecomponent',
            index=models.Index(fields=['part_of_speech'], name='grammarrule_part_of_3d0b38_idx'),
        ),
        migrations.AddConstraint(
            model_name='grammarrulecomponent',
            constraint=models.CheckConstraint(check=models.Q(('word__isnull', False), ('part_of_speech__isnull', False), _connector='OR'), name='not_both_null'),
        ),
        migrations.AddConstraint(
            model_name='grammarrulecomponent',
            constraint=models.UniqueConstraint(fields=('grammar_rule', 'rule_index'), name='grammar_rule_index_unique'),
        ),
    ]
