# Generated by Django 4.2.2 on 2023-06-15 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('is_user_added', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRuleComponent',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('part_of_speech', models.IntegerField(choices=[(1, 'Noun'), (2, 'Pronoun'), (3, 'Verb'), (4, 'Adjective'), (5, 'Adverb'), (6, 'NumberWord'), (7, 'Interjection'), (8, 'Onomatopoeia'), (9, 'FunctionWord'), (10, 'Conjunction'), (11, 'MeasureWord'), (12, 'Preposition'), (13, 'Particle'), (14, 'Predicate'), (15, 'Subject'), (16, 'Object')], null=True)),
                ('rule_index', models.IntegerField()),
                ('optional', models.BooleanField(default=False)),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarrule')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'indexes': [models.Index(fields=['word'], name='grammarrule_word_id_5a2a57_idx'), models.Index(fields=['part_of_speech'], name='grammarrule_part_of_3d0b38_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='grammarrulecomponent',
            constraint=models.CheckConstraint(check=models.Q(('word__isnull', False), ('part_of_speech__isnull', False), _connector='OR'), name='not_both_null'),
        ),
        migrations.AddConstraint(
            model_name='grammarrulecomponent',
            constraint=models.UniqueConstraint(fields=('grammar_rule', 'rule_index'), name='grammar_rule_index_unique'),
        ),
    ]
