# Generated by Django 4.2.2 on 2023-06-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grammarruleexample',
            constraint=models.UniqueConstraint(fields=('grammar_rule', 'hanzi_display'), name='grammar_rule_display_index_unique'),
        ),
    ]
