# Generated by Django 4.2.2 on 2023-06-16 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0002_alter_grammarrule_id_alter_grammarrulecomponent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRuleExamplePrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('response', models.TextField(null=True)),
                ('model', models.TextField()),
                ('usage_tokens', models.IntegerField()),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarrule')),
            ],
            options={
                'indexes': [models.Index(fields=['grammar_rule'], name='grammarrule_grammar_88767b_idx')],
            },
        ),
    ]
