# Generated by Django 4.2.2 on 2023-06-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0002_grammarruleexample_grammar_rule_display_index_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarrule',
            name='fetch_example_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
