# Generated by Django 4.2.2 on 2023-06-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0003_grammarruleexampleprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarruleexampleprompt',
            name='parse_version',
            field=models.IntegerField(choices=[(1, 'Version1')], null=True),
        ),
    ]
