# Generated by Django 4.2.2 on 2023-06-17 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('grammarrules', '0003_grammarrule_fetch_example_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRuleHumanVerifiedPromptExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.TextField(choices=[('ZHCHS', 'SIMPLIFIED_MANDARIN'), ('ZHCHT', 'TRADITIONAL_MANDARIN'), ('ENG', 'ENGLISH')])),
                ('hanzi_display', models.TextField()),
                ('pinyin_display', models.TextField()),
                ('english_definition', models.TextField()),
                ('structure_use', models.TextField()),
                ('explanation', models.TextField()),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarrule')),
            ],
        ),
        migrations.AddField(
            model_name='grammarruleexampleprompt',
            name='human_verified_example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarrulehumanverifiedpromptexample'),
        ),
        migrations.CreateModel(
            name='GrammarRuleHumanVerifiedPromptExampleComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_of_speech', models.IntegerField(choices=[(1, 'Noun'), (2, 'Pronoun'), (3, 'Verb'), (4, 'Adjective'), (5, 'Adverb'), (6, 'NumberWord'), (7, 'Interjection'), (8, 'Onomatopoeia'), (9, 'FunctionWord'), (10, 'Conjunction'), (11, 'MeasureWord'), (12, 'Preposition'), (13, 'Particle'), (14, 'Predicate'), (15, 'Subject'), (16, 'Object')], null=True)),
                ('rule_index', models.IntegerField()),
                ('prompt_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarrulehumanverifiedpromptexample')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'indexes': [models.Index(fields=['word'], name='grammarrule_word_id_a7b8dc_idx'), models.Index(fields=['part_of_speech'], name='grammarrule_part_of_7a3530_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='grammarrulehumanverifiedpromptexamplecomponent',
            constraint=models.CheckConstraint(check=models.Q(('word__isnull', False), ('part_of_speech__isnull', False), _connector='OR'), name='human_example_not_both_null'),
        ),
        migrations.AddConstraint(
            model_name='grammarrulehumanverifiedpromptexamplecomponent',
            constraint=models.UniqueConstraint(fields=('prompt_example', 'rule_index'), name='human_prompt_example_rule_index_unique'),
        ),
        migrations.AddIndex(
            model_name='grammarrulehumanverifiedpromptexample',
            index=models.Index(fields=['grammar_rule'], name='grammarrule_grammar_5d6710_idx'),
        ),
    ]
