# Generated by Django 4.2.2 on 2023-06-16 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('grammarrules', '0004_grammarruleexampleprompt_parse_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRuleExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_definition', models.TextField()),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarrule')),
            ],
        ),
        migrations.AddField(
            model_name='grammarruleexampleprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GrammarRuleExampleComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('example_index', models.IntegerField()),
                ('grammar_rule_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarruleexample')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
        migrations.AddField(
            model_name='grammarruleexample',
            name='grammar_rule_example_prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarruleexampleprompt'),
        ),
        migrations.AddConstraint(
            model_name='grammarruleexamplecomponent',
            constraint=models.UniqueConstraint(fields=('grammar_rule_example', 'example_index'), name='grammar_rule_example_component_index_unique'),
        ),
        migrations.AddIndex(
            model_name='grammarruleexample',
            index=models.Index(fields=['grammar_rule'], name='grammarrule_grammar_20fba3_idx'),
        ),
        migrations.AddConstraint(
            model_name='grammarruleexample',
            constraint=models.UniqueConstraint(fields=('grammar_rule_example_prompt',), name='grammar_rule_example_index_unique'),
        ),
    ]
