# Generated by Django 4.2.2 on 2023-06-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0004_grammarrulehumanverifiedpromptexample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarrulehumanverifiedpromptexample',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
