# Generated by Django 4.2.2 on 2023-06-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0005_grammarrulehumanverifiedpromptexample_uses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarrulehumanverifiedpromptexample',
            name='english_definition',
        ),
        migrations.AlterField(
            model_name='grammarrulecomponent',
            name='part_of_speech',
            field=models.IntegerField(choices=[(1, 'Noun'), (2, 'Pronoun'), (3, 'Verb'), (4, 'Adjective'), (5, 'Adverb'), (6, 'NumberWord'), (7, 'Interjection'), (8, 'Onomatopoeia'), (9, 'FunctionWord'), (10, 'Conjunction'), (11, 'MeasureWord'), (12, 'Preposition'), (13, 'Particle'), (14, 'Predicate'), (15, 'Subject'), (16, 'Object'), (17, 'Place')], null=True),
        ),
        migrations.AlterField(
            model_name='grammarrulehumanverifiedpromptexamplecomponent',
            name='part_of_speech',
            field=models.IntegerField(choices=[(1, 'Noun'), (2, 'Pronoun'), (3, 'Verb'), (4, 'Adjective'), (5, 'Adverb'), (6, 'NumberWord'), (7, 'Interjection'), (8, 'Onomatopoeia'), (9, 'FunctionWord'), (10, 'Conjunction'), (11, 'MeasureWord'), (12, 'Preposition'), (13, 'Particle'), (14, 'Predicate'), (15, 'Subject'), (16, 'Object'), (17, 'Place')], null=True),
        ),
    ]
