# Generated by Django 4.2.2 on 2023-06-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0005_grammarruleexample_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grammarruleexample',
            name='grammar_rule_example_index_unique',
        ),
        migrations.AddIndex(
            model_name='grammarruleexample',
            index=models.Index(fields=['grammar_rule_example_prompt'], name='grammarrule_grammar_e90a23_idx'),
        ),
    ]
