# Generated by Django 4.2.2 on 2023-06-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0006_remove_grammarrulehumanverifiedpromptexample_english_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarrulecomponent',
            name='grammar_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_rule_components', to='grammarrules.grammarrule'),
        ),
    ]
