# Generated by Django 4.2.2 on 2023-06-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0007_alter_grammarrulecomponent_grammar_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarrule',
            name='language_code',
            field=models.TextField(choices=[('ZHCHS', 'SIMPLIFIED_MANDARIN'), ('ZHCHT', 'TRADITIONAL_MANDARIN'), ('ENG', 'ENGLISH')], default='LanguageCode.SIMPLIFIED_MANDARIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grammarruleexamplecomponent',
            name='grammar_rule_example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_rule_example_components', to='grammarrules.grammarruleexample'),
        ),
    ]
