# Generated by Django 4.2.2 on 2023-07-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0010_alter_grammarrulecomponent_part_of_speech_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarrule',
            name='hsk_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
