# Generated by Django 4.2.2 on 2023-07-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0011_grammarrule_hsk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarruleexampleprompt',
            name='is_usable',
            field=models.BooleanField(default=True),
        ),
    ]
