# Generated by Django 4.2.2 on 2023-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0012_grammarruleexampleprompt_is_usable'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarruleexample',
            name='contains_non_labeled_words',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grammarruleexample',
            name='max_hsk_level',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
