# Generated by Django 4.2.2 on 2023-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammarrules', '0013_grammarruleexample_contains_non_labeled_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarruleexample',
            name='validation_score',
            field=models.IntegerField(null=True),
        ),
    ]
