#!/bin/bash
set -euo pipefail

export GRAMMARGROVE_GIT_SHA=$(git rev-parse --short HEAD) && docker compose --no-ansi -f /root/grammargrove/prod-compose.yaml run certbot renew
docker compose --no-ansi -f /root/grammargrove/prod-compose.yaml kill -s SIGHUP proxy
docker system prune -af
