#!/bin/bash
set -euo pipefail

docker-compose --no-ansi -f /root/grammargrove/prod-compose.yaml run certbot renew
docker-compose --no-ansi -f /root/grammargrove/prod-compose.yaml kill -s SIGHUP proxy
docker system prune -af
