# Generated by Django 4.2.2 on 2023-07-21 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usergrammarrules', '0004_usergrammarruleentry_added_by'),
        ('uservocabulary', '0003_uservocabularyentry_added_by'),
        ('grammarrules', '0013_grammarruleexample_contains_non_labeled_words_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSessionQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grammar_rule_example', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grammarrules.grammarruleexample')),
                ('practice_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicesession.practicesession')),
                ('user_grammar_rule_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usergrammarrules.usergrammarruleentry')),
                ('user_vocabulary_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uservocabulary.uservocabularyentry')),
            ],
        ),
    ]
