# Generated by Django 4.2.2 on 2023-07-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practicesession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesessionquestion',
            name='practice_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practicesession.practicesession'),
        ),
    ]
