# Generated by Django 4.2.2 on 2023-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='daily_practice_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
