# Generated by Django 4.2.2 on 2023-07-27 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uservocabulary', '0003_uservocabularyentry_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservocabularyentry',
            name='notes',
        ),
        migrations.CreateModel(
            name='UserVocabularyNote',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_vocabulary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uservocabulary.uservocabularyentry')),
            ],
            options={
                'indexes': [models.Index(fields=['user_vocabulary_entry'], name='uservocabul_user_vo_12d950_idx')],
            },
        ),
    ]
