# Generated by Django 4.2.2 on 2023-07-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uservocabulary', '0004_remove_uservocabularyentry_notes_uservocabularynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabularynote',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uservocabularynote',
            name='user_vocabulary_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='uservocabulary.uservocabularyentry'),
        ),
    ]
