# Generated by Django 4.2.2 on 2023-07-27 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uservocabulary', '0005_uservocabularynote_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabularynote',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
